[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
version = "^0.8.0"
features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "debug-print",
]
