//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "freight_forwarder")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub company_name: String,
    pub telephone_number: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::shipping_order::Entity")]
    ShippingOrder,
}

impl Related<super::shipping_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
