//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::freight_forwarder::Entity as FreightForwarder;
pub use super::shipping_item::Entity as ShippingItem;
pub use super::shipping_order::Entity as ShippingOrder;
pub use super::storage::Entity as Storage;
pub use super::warehouse::Entity as Warehouse;
