//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "shipping_order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub num: i64,
    pub company_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::freight_forwarder::Entity",
        from = "Column::CompanyId",
        to = "super::freight_forwarder::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FreightForwarder,
    #[sea_orm(has_many = "super::shipping_item::Entity")]
    ShippingItem,
}

impl Related<super::freight_forwarder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreightForwarder.def()
    }
}

impl Related<super::shipping_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
