//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "shipping_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_num: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub nth: i16,
    pub shipment_date: Date,
    pub quantity: i32,
    pub ton: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::shipping_order::Entity",
        from = "Column::OrderNum",
        to = "super::shipping_order::Column::Num",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingOrder,
}

impl Related<super::shipping_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
